/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("buildlogic.kotlin-library-conventions")
    kotlin("plugin.allopen") version "1.9.24"
}

dependencies {
    api(platform(libs.spring.boot.dependencies))
    api(platform(libs.spring.cloud.dependencies))

    implementation(libs.commons.lang3)
    implementation(libs.commons.io)

    // Jakarta EE
    compileOnly("jakarta.validation:jakarta.validation-api")
    compileOnly("jakarta.persistence:jakarta.persistence-api")
    compileOnly("jakarta.transaction:jakarta.transaction-api")

    compileOnly("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.springframework.cloud:spring-cloud-commons")
}

allOpen {
    annotation("jakarta.persistence.Entity")
    annotation("jakarta.persistence.Table")
    annotation("jakarta.persistence.Column")
    annotation("jakarta.persistence.Id")
    annotation("jakarta.persistence.GeneratedValue")
    annotation("jakarta.persistence.Embeddable")
    annotation("jakarta.persistence.MappedSuperclass")
}