/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    id("buildlogic.kotlin-application-conventions")
    id("org.springframework.boot") version "3.3.0"
    kotlin("plugin.spring") version "1.9.24"
}


dependencies {

    implementation(project(":microsphere-devops-service"))

    implementation(libs.log4j2.core)


    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    // implementation("io.github.microsphere-projects:microsphere-spring-boot-actuator")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
