/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    implementation(libs.commons.lang3)
    implementation(project(":microsphere-devops-api"))
}
