/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    implementation(libs.commons.lang3)
    implementation(project(":microsphere-devops-api"))
}
