/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    id("buildlogic.kotlin-library-conventions")
    // Apply the spring plugin to add support for Spring specific features
    kotlin("plugin.spring") version "1.9.24"
}


dependencies {

    // Internal Project
    api(project(":microsphere-devops-repository"))

    // Import the BOMs
    // Microsphere Spring Cloud Alibaba Dependencies
    api(platform(libs.spring.cloud.alibaba.dependencies))
    // Microsphere Spring Boot Dependencies
    // api(platform(libs.microsphere.spring.boot.dependencies))
    // Microsphere Spring Cloud Dependencies
    api(platform(libs.microsphere.spring.cloud.dependencies))
    // Nacos Open API
    api(libs.microsphere.nacos.openapi)

    // Apache HTTP Client
    api("org.apache.httpcomponents:httpclient")

    // Google Gson
    api("com.google.code.gson:gson")

    // Bean Validation Vender - Hibernate Validator
    api("org.hibernate.validator:hibernate-validator")

    // Spring Cloud Commons
    api("org.springframework.cloud:spring-cloud-commons")

    // Nacos Discovery
    api("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery")

    // Testing
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
