/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    compileOnly(platform(libs.spring.boot.dependencies))
    compileOnly(platform(libs.microsphere.spring.dependencies))

    // Microsphere Spring
    api("io.github.microsphere-projects:microsphere-spring-context")

    // Jakarta EE
    compileOnly("jakarta.validation:jakarta.validation-api")
    compileOnly("jakarta.persistence:jakarta.persistence-api")
    compileOnly("jakarta.transaction:jakarta.transaction-api")

    // Spring Framework
    compileOnly("org.springframework:spring-context")
    compileOnly("org.springframework:spring-aop")
    compileOnly("org.springframework:spring-orm")

    // JPA Vender - Hibernate
    compileOnly("org.hibernate.orm:hibernate-core")
}