spring:
  application:
    name: microsphere-devops
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers : true
        globally_quoted_identifiers_skip_column_definitions : true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'