spring:
  application:
    name: microsphere-devops
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers : true
        globally_quoted_identifiers_skip_column_definitions : true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'


---
spring:
  config:
    activate:
      on-profile: nacos
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
